name: 'Apply ESLint on back-end'
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Run-ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install packages
        run: "npm i && npm i -D"
      - name: Run eslint
        run: "npx eslint . --ext .js,.jsx,.ts,.tsx"
